### ISSUE TITLE
Support for no hash-bangs / HTML5 mode URLs

### ISSUE THREAD

**Issue by jonjhiggins** [Producters/express-crawler-snapshots#5]
Hi

Is there an option to support HTML5 URLs (e.g. http://example.com/about instead of http://example.com/#!/about )? 

I got it working by removing the `"#!" +` on line 35 of index.js, just wanted to check if there was an option I'd missed?

Other than that it works great!

Cheers
Jon

**Comment by domasx2** [comment]
Hi,

I don't quite understand why you're having this problem: if your app uses html5 urls without `#!`, then a crawler shouldn't generate a _escaped_fragment_ query param at all, but just call the normal http://example.com/about. This lib will detect bot request via user agent string and prerender the page.
If your app does use urls with `#!`, then it should be able to handle them

Unless I misunderstood something, this package handles _escaped_fragment_ semantics as per google's spec: https://developers.google.com/webmasters/ajax-crawling/docs/specification?hl=en

**Comment by jonjhiggins** [comment]
Hi

I'm referring to a single-page JS app, rather than a standard website, where all routing is done by JS still but using the HTML5 history / pushstatte format - rather than hashbangs. This is touched on in this section of the Google spec: https://developers.google.com/webmasters/ajax-crawling/docs/specification?hl=en#pages-without-hash-fragments 

Further examples of this format would be [enabling the HTML5 url mode in Angular](https://docs.angularjs.org/guide/$location#hashbang-and-html5-modes) or comparing the HTML source (before JS runs) of these two URLs:

https://www.redbullsoundselect.com/discover
https://www.redbullsoundselect.com/?_escaped_fragment_=discover

as you can see the first URL is not crawlable by Google, but the second example is

**Comment by domasx2** [comment]
yeah, i know how spas work. what i don't get is, if your app uses htm5
history mode, what do you need escaped_fragment semantics for, considering
its a hashbang related feature? how/why do you end up with an url that has
escapef_fragment in it?

**Comment by jonjhiggins** [comment]
If you view the source of the two Redbull examples above you will see the first is uncrawlable by Google - it relies on async javascript to run to display the content.

By adding <meta name="fragment" content="!”> to their HTML the Redbull developers have told Google to request the same page with _escaped_fragment_, which allows them to serve a static HTML version that Google can crawl.

**Comment by domasx2** [comment]
So redbull uses _escaped_fragment_ as a mechanism for detecting search engine crawlers.
The prefered way for this middleware to detect crawlers is by reading the `"User-Agent"` header. Just remove the  `<meta name="fragment" content="!”>` element and everything should work fine. You can test it using curl:

``` sh
curl -L -A "Googlebot/2.1 (+http://www.google.com/bot.html)" https://www.example.com/about
```

express-crawler-snapshots would then read the User-Agent header, detect googlebot, proxy this request to a phantomjs instance. Phantomjs then renders it normally as a browser would, async javascript, ajax and all that. Resulting html then gets proxied back. Easy, no need to worry about transforming URL back and forth.

I think using _escaped_fragment_ to detect crawlers when you use html5 history API is bit of a messy workaround. `"User-Agent"` header is meant for precisely this purpose, and doesn't require modifying your html in any way.

If you're still not convinced, I can add 'htmlPrefix' option to allow configuring hashbang prefix or removing it entirely though, no problem :)

**Comment by jonjhiggins** [comment]
Ah right, I didn’t realise express-crawler-snapshots already handled that scenario already! I thought it was all done via _escaped_parameter_, must have misread documentation. Feel free to close off the issue :) And sorry for timewasting!

**Comment by domasx2** [comment]
Np!  I'll see if I can clarify the readme :)
